### ISSUE TITLE
Dependency issue when installing from pip

### ISSUE THREAD

**Issue by electroducer** [zerok/zs.bibtex#4]
Your setup.py is asking for pyparsing 1.5.0, which is messing things up severely when installing using pip. Why did you force it to require v.1.5.0? Right now, the only way to install is by using the --no-dependencies flag.

**Comment by zerok** [comment]
After 6 years the only explanation I can come up with is "I was young and didn't know any better" ;) I will look into it this weekend. I need to clean that package up before I can release anything with changed dependencies :)

**Comment by electroducer** [comment]
No worries, it looked like it hadn't been touched in a while. Looks like it might not be set to work on python 3, so I think I'm going to just make something simple to meet my needs for now. Let me know if you get this working though!

**Comment by zerok** [comment]
Yup, I needed it back when I was writing on my master thesis or some other paper and haven't touched it ever since :) I will definitely look into it this weekend if only to have another package in PyPI that is Python 3 compatible :)

**Comment by zerok** [comment]
@electroducer I've just removed the version restriction on pyparsing with 422fa83d0e442c5efcd707e0d6f8caa45f958426 . I will most likely do a 1.0 release this weekend once I have the package working with Python 3.4. The API will stay completely identical if I can somehow manage it.

**Comment by zerok** [comment]
Should now be resolved :)

**Comment by electroducer** [comment]
I just did a quick test with Python 3.4. It installed fine via pip and did seem to work fine with my data, though I was only trying to parse strings. Thanks for taking the time to get this fixed up so quick!
